# Generated by Django 4.1.3 on 2023-01-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
